version: '2.2'

services:
  api:
    ports:
    - "8000:8000"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: agrocult_backend:${AGROCULT_BACKEND_VERSION:-latest}
    volumes:
    - ./:/app/src/
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:13.4-buster
    hostname: agrocult_backend-db
    env_file:
      - .env.db
    volumes:
    - agrocult_backend-db-data:/var/lib/postgresql/data
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - agrocult_backend
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    user: 1000:1000
    volumes:
    - ./:/app/src/
    image: agrocult_backend:${AGROCULT_BACKEND_VERSION:-latest}
    restart: "no"
    command: sh -c "aerich migrate && aerich upgrade"
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: agrocult_backend-redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 1s
      timeout: 3s
      retries: 30


volumes:
  agrocult_backend-db-data:
    name: agrocult_backend-db-data
